apiVersion: v1

kind: Pod

metadata:
    name: simple-webapp-color
    labels:
        name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: nginx
      ports:
        - containerPort:8080
      env:
      -name: APP_COLOR
       valueFrom:
             configMapKeyRef:
                name: app-config
                key: APP_COLOR
